import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.NANSHUO_CONFIG||{}; const configured=cfg.supabaseUrl&&cfg.supabaseKey&&!cfg.supabaseUrl.includes('PASTE_')&&!cfg.supabaseKey.includes('PASTE_');
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let sb=null, settings=null, brands=[], jobs=[], entityType=null, editingId=null;
function show(id){['setup-screen','login-screen','dashboard'].forEach(x=>$('#'+x).classList.add('hidden'));$('#'+id).classList.remove('hidden')}
function toast(msg){const el=$('#admin-toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function busy(btn,on,label='Đang xử lý...'){if(!btn)return;btn.disabled=on;if(on){btn.dataset.old=btn.innerHTML;btn.innerHTML=`<i class="fa-solid fa-circle-notch fa-spin mr-2"></i>${label}`}else if(btn.dataset.old)btn.innerHTML=btn.dataset.old}
if(!configured){show('setup-screen')}else{sb=createClient(cfg.supabaseUrl,cfg.supabaseKey);initAuth()}
async function initAuth(){const {data:{session}}=await sb.auth.getSession();if(session)await enterDashboard(session.user);else show('login-screen');sb.auth.onAuthStateChange(async(e,s)=>{if(e==='SIGNED_IN'&&s)await enterDashboard(s.user);if(e==='SIGNED_OUT')show('login-screen')})}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('#login-btn');busy(btn,true,'Đang đăng nhập...');$('#login-error').classList.add('hidden');const {error}=await sb.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});busy(btn,false);if(error){$('#login-error').textContent=error.message;$('#login-error').classList.remove('hidden')}})
$('#logout-btn').addEventListener('click',()=>sb?.auth.signOut());
async function enterDashboard(user){show('dashboard');$('#admin-email').textContent=user.email;await loadAll();fillSettings();renderBrands();renderJobs()}
async function loadAll(){const [s,b,j]=await Promise.all([sb.from('site_settings').select('*').eq('id',1).maybeSingle(),sb.from('brands').select('*').order('sort_order'),sb.from('jobs').select('*').order('sort_order')]);if(s.error)throw s.error;if(b.error)throw b.error;if(j.error)throw j.error;settings=s.data||{id:1,hero:{},about:{},contact:{}};brands=b.data||[];jobs=j.data||[]}
function v(id,val){const el=$(id);if(el)el.value=val??''}
function fillSettings(){const h=settings.hero||{},a=settings.about||{},c=settings.contact||{};v('#hero-eyebrow-vi',h.eyebrow_vi);v('#hero-eyebrow-zh',h.eyebrow_zh);v('#hero-title-vi',h.title_vi);v('#hero-title-zh',h.title_zh);v('#hero-text-vi',h.text_vi);v('#hero-text-zh',h.text_zh);v('#hero-image',h.image);preview('#hero-preview',h.image);v('#about-title-vi',a.title_vi);v('#about-title-zh',a.title_zh);v('#about-text-vi',a.text_vi);v('#about-text-zh',a.text_zh);v('#contact-company',c.company);v('#contact-address',c.address);v('#contact-email',c.email);v('#contact-phone',c.phone);v('#contact-zalo',c.zalo)}
function preview(sel,url){const el=$(sel);if(url){el.src=url;el.classList.remove('hidden')}else el.classList.add('hidden')}
$('#settings-form').addEventListener('submit',async e=>{e.preventDefault();const hero={eyebrow_vi:$('#hero-eyebrow-vi').value,eyebrow_zh:$('#hero-eyebrow-zh').value,title_vi:$('#hero-title-vi').value,title_zh:$('#hero-title-zh').value,text_vi:$('#hero-text-vi').value,text_zh:$('#hero-text-zh').value,image:$('#hero-image').value};const about={title_vi:$('#about-title-vi').value,title_zh:$('#about-title-zh').value,text_vi:$('#about-text-vi').value,text_zh:$('#about-text-zh').value};const contact={company:$('#contact-company').value,address:$('#contact-address').value,email:$('#contact-email').value,phone:$('#contact-phone').value,zalo:$('#contact-zalo').value};const {error}=await sb.from('site_settings').upsert({id:1,hero,about,contact,updated_at:new Date().toISOString()});if(error)return toast('Lỗi: '+error.message);settings={id:1,hero,about,contact};toast('Đã lưu trang chủ')})
$('#hero-image').addEventListener('input',e=>preview('#hero-preview',e.target.value));$('#hero-upload').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;const url=await uploadImage(file,'hero');if(url){$('#hero-image').value=url;preview('#hero-preview',url);toast('Đã upload ảnh bìa')}})
async function uploadImage(file,prefix='site'){if(file.size>6*1024*1024){toast('Ảnh tối đa 6MB');return null}const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const safe=`${prefix}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await sb.storage.from('site-images').upload(safe,file,{cacheControl:'3600',upsert:false});if(error){toast('Upload lỗi: '+error.message);return null}return sb.storage.from('site-images').getPublicUrl(safe).data.publicUrl}

document.querySelectorAll('.tab-btn').forEach(btn=>btn.onclick=()=>switchTab(btn.dataset.tab));function switchTab(tab){document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$('#tab-'+tab).classList.remove('hidden');document.querySelectorAll('.tab-btn').forEach(x=>x.className='tab-btn rounded-full bg-white border border-black/10 px-5 py-3 text-xs font-bold');const b=document.querySelector(`[data-tab="${tab}"]`);b.className='tab-btn rounded-full bg-ink text-white px-5 py-3 text-xs font-bold'}
function renderBrands(){$('#brands-admin-list').innerHTML=brands.map(b=>`<article class="bg-white rounded-[26px] border border-black/5 overflow-hidden"><div class="aspect-[16/9] bg-stone-100 relative">${b.image_url?`<img src="${esc(b.image_url)}" class="w-full h-full object-cover">`:`<div class="absolute inset-0 grid place-items-center text-gray-300 display text-3xl font-extrabold">${esc(b.name)}</div>`}<span class="absolute top-3 right-3 text-[10px] font-bold rounded-full px-2.5 py-1 ${b.active?'bg-emerald text-white':'bg-white text-gray-500'}">${b.active?'Đang hiển thị':'Đang ẩn'}</span></div><div class="p-5"><div class="display text-xl font-extrabold">${esc(b.name)}</div><div class="text-xs text-gray-500 mt-2">${esc((b.locations||[]).join(' · '))}</div><button data-brand="${b.id}" class="edit-brand mt-4 rounded-full bg-ink text-white px-4 py-2.5 text-xs font-bold">Chỉnh sửa</button></div></article>`).join('');document.querySelectorAll('.edit-brand').forEach(b=>b.onclick=()=>openBrand(b.dataset.brand))}
function renderJobs(){$('#jobs-admin-list').innerHTML=jobs.map(j=>`<article class="bg-white rounded-[24px] border border-black/5 p-5 md:p-6 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div class="flex items-center gap-2"><span class="text-[10px] font-bold uppercase tracking-[.14em] text-gray-400">${esc(j.category)}</span>${j.hot?'<span class="text-[9px] bg-emerald/10 text-emerald rounded-full px-2 py-1 font-bold">HOT</span>':''}${!j.active?'<span class="text-[9px] bg-gray-100 text-gray-500 rounded-full px-2 py-1 font-bold">ẨN</span>':''}</div><div class="display text-xl font-extrabold mt-1">${esc(j.title_vi)}</div><div class="text-xs text-gray-500 mt-2">${esc(j.location)} · ${esc(j.salary)}</div></div><button data-job="${j.id}" class="edit-job rounded-full bg-ink text-white px-4 py-2.5 text-xs font-bold">Chỉnh sửa</button></article>`).join('');document.querySelectorAll('.edit-job').forEach(b=>b.onclick=()=>openJob(b.dataset.job))}
$('#new-brand').onclick=()=>openBrand(null);$('#new-job').onclick=()=>openJob(null);
function field(label,name,value='',type='text',extra=''){if(type==='textarea')return `<div class="${extra}"><label class="form-label">${label}</label><textarea name="${name}" rows="4" class="form-input">${esc(value)}</textarea></div>`;if(type==='checkbox')return `<label class="${extra} flex items-center gap-3 bg-paper rounded-2xl px-4 py-3.5"><input name="${name}" type="checkbox" ${value?'checked':''} class="w-4 h-4"><span class="text-sm font-bold">${label}</span></label>`;return `<div class="${extra}"><label class="form-label">${label}</label><input name="${name}" type="${type}" value="${esc(value)}" class="form-input"></div>`}
function openModal(){ $('#editor-modal').classList.remove('hidden');document.body.style.overflow='hidden'}function closeModal(){$('#editor-modal').classList.add('hidden');document.body.style.overflow=''}document.querySelectorAll('[data-modal-close]').forEach(x=>x.onclick=closeModal);
function openBrand(id){entityType='brand';editingId=id?Number(id):null;const b=editingId?brands.find(x=>x.id===editingId):{name:'',desc_vi:'',desc_zh:'',locations:[],image_url:'',active:true,sort_order:brands.length+1};$('#entity-kicker').textContent='Brand';$('#entity-title').textContent=editingId?'Chỉnh sửa thương hiệu':'Thêm thương hiệu';$('#entity-delete').classList.toggle('hidden',!editingId);$('#entity-fields').innerHTML=field('Tên thương hiệu','name',b.name)+field('Thứ tự','sort_order',b.sort_order,'number')+field('Mô tả VI','desc_vi',b.desc_vi,'textarea')+field('Mô tả 中文','desc_zh',b.desc_zh,'textarea')+field('Cửa hàng (mỗi dòng 1 địa điểm)','locations',(b.locations||[]).join('\n'),'textarea','md:col-span-2')+`<div class="md:col-span-2"><label class="form-label">Ảnh thương hiệu</label><div class="grid md:grid-cols-[1fr_auto] gap-3"><input name="image_url" value="${esc(b.image_url)}" class="form-input"><label class="rounded-2xl bg-bronze text-white px-5 py-3.5 text-sm font-bold cursor-pointer text-center"><i class="fa-solid fa-cloud-arrow-up mr-2"></i>Upload<input id="entity-upload" type="file" accept="image/*" class="hidden"></label></div><img id="entity-preview" src="${esc(b.image_url)}" class="${b.image_url?'':'hidden'} mt-4 max-h-64 w-full object-cover rounded-2xl"></div>`+field('Hiển thị trên website','active',b.active,'checkbox') ;wireEntityUpload('brand');openModal()}
function openJob(id){entityType='job';editingId=id?Number(id):null;const j=editingId?jobs.find(x=>x.id===editingId):{category:'ops',title_vi:'',title_zh:'',location:'',type_vi:'Toàn thời gian',type_zh:'全职',salary:'',summary_vi:'',summary_zh:'',hot:false,active:true,sort_order:jobs.length+1};$('#entity-kicker').textContent='Job';$('#entity-title').textContent=editingId?'Chỉnh sửa vị trí':'Thêm vị trí';$('#entity-delete').classList.toggle('hidden',!editingId);$('#entity-fields').innerHTML=`<div><label class="form-label">Nhóm</label><select name="category" class="form-input"><option value="ops" ${j.category==='ops'?'selected':''}>Bán lẻ</option><option value="marketing" ${j.category==='marketing'?'selected':''}>Marketing & Brand</option><option value="design" ${j.category==='design'?'selected':''}>Thiết kế</option></select></div>`+field('Thứ tự','sort_order',j.sort_order,'number')+field('Tên vị trí VI','title_vi',j.title_vi)+field('Tên vị trí 中文','title_zh',j.title_zh)+field('Địa điểm','location',j.location)+field('Mức lương','salary',j.salary)+field('Loại công việc VI','type_vi',j.type_vi)+field('Loại công việc 中文','type_zh',j.type_zh)+field('Mô tả VI','summary_vi',j.summary_vi,'textarea')+field('Mô tả 中文','summary_zh',j.summary_zh,'textarea')+field('Đánh dấu HOT','hot',j.hot,'checkbox')+field('Hiển thị trên website','active',j.active,'checkbox');openModal()}
function wireEntityUpload(prefix){const input=$('#entity-upload');if(!input)return;input.onchange=async e=>{const file=e.target.files?.[0];if(!file)return;const url=await uploadImage(file,prefix);if(url){document.querySelector('[name="image_url"]').value=url;const p=$('#entity-preview');p.src=url;p.classList.remove('hidden');toast('Upload ảnh thành công')}}}
$('#entity-form').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.target);const obj=Object.fromEntries(fd.entries());obj.sort_order=Number(obj.sort_order)||0;obj.active=fd.has('active');if(entityType==='brand'){obj.locations=String(obj.locations||'').split('\n').map(x=>x.trim()).filter(Boolean);const q=editingId?sb.from('brands').update(obj).eq('id',editingId):sb.from('brands').insert(obj);const {error}=await q;if(error)return toast('Lỗi: '+error.message)}else{obj.hot=fd.has('hot');const q=editingId?sb.from('jobs').update(obj).eq('id',editingId):sb.from('jobs').insert(obj);const {error}=await q;if(error)return toast('Lỗi: '+error.message)}await loadAll();renderBrands();renderJobs();closeModal();toast('Đã lưu thay đổi')})
$('#entity-delete').onclick=async()=>{if(!editingId||!confirm('Bạn chắc chắn muốn xóa mục này?'))return;const table=entityType==='brand'?'brands':'jobs';const {error}=await sb.from(table).delete().eq('id',editingId);if(error)return toast('Lỗi: '+error.message);await loadAll();renderBrands();renderJobs();closeModal();toast('Đã xóa')}
