import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.NANSHUO_CONFIG||{};const configured=cfg.supabaseUrl&&cfg.supabaseKey;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let sb=null,brands=[],products=[],editingId=null,images=[];
function show(id){['setup','login','dashboard'].forEach(x=>$('#'+x).classList.add('hidden'));$('#'+id).classList.remove('hidden')}function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),2600)}
if(!configured)show('setup');else{sb=createClient(cfg.supabaseUrl,cfg.supabaseKey);init()}
async function init(){const {data:{session}}=await sb.auth.getSession();if(session)enter(session.user);else show('login');sb.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_IN'&&s)enter(s.user);if(e==='SIGNED_OUT')show('login')})}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').classList.add('hidden');const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#login-error').textContent=error.message;$('#login-error').classList.remove('hidden')}};$('#logout').onclick=()=>sb.auth.signOut();
async function enter(user){show('dashboard');$('#admin-email').textContent=user.email;await loadAll()}
async function loadAll(){const [b,p]=await Promise.all([sb.from('brands').select('*').order('sort_order'),sb.from('products').select('*').order('sort_order').order('id')]);if(b.error){toast('Lỗi brands: '+b.error.message);return}brands=b.data||[];if(p.error){products=[];$('#table-message').innerHTML='<b>Chưa có bảng products.</b> Hãy chạy file <code>catalog-setup.sql</code> trong Supabase SQL Editor một lần.';$('#table-message').classList.remove('hidden')}else{$('#table-message').classList.add('hidden');products=p.data||[]}fillFilters();render()}
function fillFilters(){const current=$('#filter-brand').value;$('#filter-brand').innerHTML='<option value="">Tất cả thương hiệu</option>'+brands.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');if([...$('#filter-brand').options].some(o=>o.value===current))$('#filter-brand').value=current;fillStoreFilter();}
function brandById(id){return brands.find(b=>Number(b.id)===Number(id))}function storeOptions(brandId,includeAll=true){const b=brandById(brandId);const arr=b&&Array.isArray(b.locations)?b.locations:[];return `${includeAll?'<option value="__all__">Tất cả cửa hàng của thương hiệu</option>':''}${arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}`}
function fillStoreFilter(){const bid=$('#filter-brand').value;const old=$('#filter-store').value;$('#filter-store').innerHTML='<option value="">Tất cả cửa hàng</option>'+(bid?storeOptions(bid,false):'');if([...$('#filter-store').options].some(o=>o.value===old))$('#filter-store').value=old}
function render(){const bid=$('#filter-brand').value,store=$('#filter-store').value,q=$('#filter-search').value.toLowerCase().trim();const list=products.filter(p=>(!bid||String(p.brand_id)===bid)&&(!store||p.store_location===store)&&(!q||[p.name_vi,p.name_zh,p.category_vi,p.sku].join(' ').toLowerCase().includes(q)));$('#product-list').innerHTML=list.map(p=>{const b=brandById(p.brand_id),img=Array.isArray(p.image_urls)&&p.image_urls[0];return `<article class="card overflow-hidden"><div class="aspect-[4/3] bg-stone-100">${img?`<img src="${esc(img)}" class="w-full h-full object-cover">`:'<div class="h-full grid place-items-center text-gray-300"><i class="fa-solid fa-image text-3xl"></i></div>'}</div><div class="p-5"><div class="text-[9px] uppercase tracking-[.15em] font-bold text-primary">${esc(b?.name||'')} · ${esc(p.store_location==='__all__'?'Tất cả cửa hàng':p.store_location)}</div><h3 class="font-bold text-lg mt-2">${esc(p.name_vi)}</h3><div class="text-xs text-gray-500 mt-2">${esc(p.category_vi||'')} ${p.price_text?'· '+esc(p.price_text):''}</div><div class="mt-4 flex items-center justify-between"><span class="text-[10px] rounded-full px-2.5 py-1 font-bold ${p.active?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'}">${p.active?'Đang hiển thị':'Đang ẩn'}</span><button data-edit="${p.id}" class="rounded-full bg-secondary text-white px-4 py-2 text-xs font-bold">Chỉnh sửa</button></div></div></article>`}).join('')||'<div class="card p-8 text-center text-gray-500 md:col-span-2 xl:col-span-3">Chưa có sản phẩm phù hợp.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openModal(Number(b.dataset.edit)))}
$('#filter-brand').onchange=()=>{fillStoreFilter();render()};$('#filter-store').onchange=render;$('#filter-search').oninput=render;$('#new-product').onclick=()=>openModal(null);
function closeModal(){$('#modal').classList.add('hidden');document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal);
function openModal(id){editingId=id;const p=id?products.find(x=>Number(x.id)===id):null;$('#modal-title').textContent=id?'Chỉnh sửa sản phẩm':'Thêm sản phẩm';$('#delete-product').classList.toggle('hidden',!id);$('#form-brand').innerHTML=brands.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');const defaultBrand=p?.brand_id||brands[0]?.id||'';$('#form-brand').value=String(defaultBrand);fillFormStores(p?.store_location||'__all__');const f=$('#product-form');['name_vi','name_zh','category_vi','category_zh','sku','price_text','description_vi','description_zh','sort_order'].forEach(n=>{f.elements[n].value=p?.[n]??(n==='sort_order'?0:'')});f.elements.active.checked=p?.active!==false;images=Array.isArray(p?.image_urls)?[...p.image_urls]:[];renderImages();$('#modal').classList.remove('hidden');document.body.style.overflow='hidden'}
function fillFormStores(selected){const bid=$('#form-brand').value;$('#form-store').innerHTML=storeOptions(bid,true);$('#form-store').value=[...$('#form-store').options].some(o=>o.value===selected)?selected:'__all__'}$('#form-brand').onchange=()=>fillFormStores('__all__');
function renderImages(){$('#image-list').innerHTML=images.map((u,i)=>`<div class="relative aspect-square rounded-2xl overflow-hidden bg-stone-100"><img src="${esc(u)}" class="w-full h-full object-cover"><button type="button" data-remove-image="${i}" class="absolute top-1.5 right-1.5 w-7 h-7 rounded-full bg-black/65 text-white text-xs"><i class="fa-solid fa-xmark"></i></button></div>`).join('');document.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{images.splice(Number(b.dataset.removeImage),1);renderImages()})}
$('#image-upload').onchange=async e=>{const files=[...(e.target.files||[])].slice(0,Math.max(0,6-images.length));if(!files.length)return;$('#upload-status').textContent='Đang upload...';for(const file of files){if(file.size>6*1024*1024){toast(`${file.name}: ảnh lớn hơn 6MB`);continue}const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`products/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const {error}=await sb.storage.from('site-images').upload(path,file,{cacheControl:'3600'});if(error){toast('Upload lỗi: '+error.message);continue}images.push(sb.storage.from('site-images').getPublicUrl(path).data.publicUrl)}$('#upload-status').textContent=`Đã có ${images.length}/6 ảnh`;renderImages();e.target.value=''};
$('#product-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const obj=Object.fromEntries(fd.entries());obj.brand_id=Number(obj.brand_id);obj.sort_order=Number(obj.sort_order)||0;obj.active=fd.has('active');obj.image_urls=images;obj.updated_at=new Date().toISOString();const res=editingId?await sb.from('products').update(obj).eq('id',editingId):await sb.from('products').insert(obj);if(res.error)return toast('Lỗi: '+res.error.message);await loadAll();closeModal();toast('Đã lưu sản phẩm')};
$('#delete-product').onclick=async()=>{if(!editingId||!confirm('Xóa sản phẩm này?'))return;const {error}=await sb.from('products').delete().eq('id',editingId);if(error)return toast('Lỗi: '+error.message);await loadAll();closeModal();toast('Đã xóa sản phẩm')};
