-- ================================================================
-- NANSHUO PRODUCT CATALOG - SUPABASE SETUP
-- Chạy file này MỘT LẦN trong Supabase > SQL Editor > New query
-- Không xóa hay thay đổi bảng brands/jobs hiện có.
-- ================================================================

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.brands(id) on delete cascade,
  store_location text not null default '__all__',
  sku text not null default '',
  name_vi text not null,
  name_zh text not null default '',
  category_vi text not null default 'Sản phẩm',
  category_zh text not null default '',
  price_text text not null default '',
  description_vi text not null default '',
  description_zh text not null default '',
  image_urls jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_images_is_array check (jsonb_typeof(image_urls) = 'array')
);

create index if not exists products_brand_store_idx on public.products (brand_id, store_location);
create index if not exists products_active_sort_idx on public.products (active, sort_order);

alter table public.products enable row level security;

drop policy if exists "public read active products" on public.products;
create policy "public read active products"
on public.products for select to anon
using (active = true);

drop policy if exists "authenticated read all products" on public.products;
create policy "authenticated read all products"
on public.products for select to authenticated
using (true);

drop policy if exists "admin insert products" on public.products;
create policy "admin insert products"
on public.products for insert to authenticated
with check (true);

drop policy if exists "admin update products" on public.products;
create policy "admin update products"
on public.products for update to authenticated
using (true) with check (true);

drop policy if exists "admin delete products" on public.products;
create policy "admin delete products"
on public.products for delete to authenticated
using (true);

-- site-images đã được tạo trong supabase-setup.sql hiện tại.
-- Nếu bucket chưa tồn tại, lệnh dưới đây tạo mới an toàn.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-images','site-images',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true, file_size_limit=6291456, allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "public read site images" on storage.objects;
create policy "public read site images" on storage.objects for select to public using (bucket_id = 'site-images');
drop policy if exists "admin insert site images" on storage.objects;
create policy "admin insert site images" on storage.objects for insert to authenticated with check (bucket_id = 'site-images');
drop policy if exists "admin update site images" on storage.objects;
create policy "admin update site images" on storage.objects for update to authenticated using (bucket_id = 'site-images') with check (bucket_id = 'site-images');
drop policy if exists "admin delete site images" on storage.objects;
create policy "admin delete site images" on storage.objects for delete to authenticated using (bucket_id = 'site-images');
