-- ================================================================
-- NANSHUO FASHION CATALOG UPGRADE
-- Chạy MỘT LẦN trong Supabase > SQL Editor > New query
-- Bổ sung ảnh/mô tả riêng cho từng gian hàng.
-- Danh mục thời trang dùng các cột category_vi/category_zh hiện có,
-- nên KHÔNG cần thay đổi bảng products.
-- ================================================================

create table if not exists public.store_profiles (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.brands(id) on delete cascade,
  store_location text not null,
  image_url text not null default '',
  description_vi text not null default '',
  description_zh text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (brand_id, store_location)
);

create index if not exists store_profiles_brand_idx
  on public.store_profiles (brand_id, active);

alter table public.store_profiles enable row level security;

drop policy if exists "public read active store profiles" on public.store_profiles;
create policy "public read active store profiles"
on public.store_profiles for select to anon
using (active = true);

drop policy if exists "authenticated read store profiles" on public.store_profiles;
create policy "authenticated read store profiles"
on public.store_profiles for select to authenticated
using (true);

drop policy if exists "admin insert store profiles" on public.store_profiles;
create policy "admin insert store profiles"
on public.store_profiles for insert to authenticated
with check (true);

drop policy if exists "admin update store profiles" on public.store_profiles;
create policy "admin update store profiles"
on public.store_profiles for update to authenticated
using (true) with check (true);

drop policy if exists "admin delete store profiles" on public.store_profiles;
create policy "admin delete store profiles"
on public.store_profiles for delete to authenticated
using (true);

grant select on public.store_profiles to anon;
grant select, insert, update, delete on public.store_profiles to authenticated;
grant usage, select on sequence public.store_profiles_id_seq to authenticated;

-- Đảm bảo bucket hiện tại cho phép ảnh gian hàng.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-images','site-images',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update
set public=true,
    file_size_limit=6291456,
    allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];
