-- ================================================================
-- NANSHUO ORDERS - SUPABASE SETUP
-- Chạy MỘT LẦN trong Supabase > SQL Editor > New query
-- Bảng này lưu thông tin khách để admin liên hệ xác nhận đơn hàng.
-- Dữ liệu khách KHÔNG được phép đọc công khai.
-- ================================================================

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  brand_id bigint references public.brands(id) on delete set null,
  brand_name text not null default '',
  store_location text not null default '',
  product_name text not null,
  product_sku text not null default '',
  price_text text not null default '',
  quantity integer not null default 1 check (quantity between 1 and 99),
  customer_name text not null check (char_length(trim(customer_name)) between 2 and 100),
  phone text not null check (char_length(trim(phone)) between 8 and 20),
  address text not null check (char_length(trim(address)) between 5 and 300),
  note text not null default '',
  status text not null default 'new' check (status in ('new','contacted','confirmed','completed','cancelled')),
  privacy_accepted boolean not null default true check (privacy_accepted = true),
  source_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status, created_at desc);
create index if not exists orders_brand_store_idx on public.orders (brand_id, store_location);

alter table public.orders enable row level security;

-- Khách truy cập website chỉ được GỬI đơn mới, tuyệt đối không được đọc danh sách đơn.
drop policy if exists "public create orders" on public.orders;
create policy "public create orders"
on public.orders for insert to anon
with check (status = 'new' and privacy_accepted = true);

-- Admin đăng nhập Supabase được xem và quản lý đơn.
drop policy if exists "authenticated read orders" on public.orders;
create policy "authenticated read orders"
on public.orders for select to authenticated
using (true);

drop policy if exists "authenticated create orders" on public.orders;
create policy "authenticated create orders"
on public.orders for insert to authenticated
with check (privacy_accepted = true);

drop policy if exists "authenticated update orders" on public.orders;
create policy "authenticated update orders"
on public.orders for update to authenticated
using (true) with check (true);

drop policy if exists "authenticated delete orders" on public.orders;
create policy "authenticated delete orders"
on public.orders for delete to authenticated
using (true);

-- Quyền bảng. RLS phía trên vẫn quyết định bản ghi nào được thao tác.
grant insert on public.orders to anon;
grant select, insert, update, delete on public.orders to authenticated;
