import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const cfg=window.NANSHUO_CONFIG||{};const configured=cfg.supabaseUrl&&cfg.supabaseKey;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let sb=null,brands=[],managers=[];
function show(id){['setup','login','dashboard','denied'].forEach(x=>$('#'+x).classList.add('hidden'));$('#'+id).classList.remove('hidden')}function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.remove('hidden');setTimeout(()=>e.classList.add('hidden'),3000)}
if(!configured)show('setup');else{sb=createClient(cfg.supabaseUrl,cfg.supabaseKey);init()}
async function init(){const {data:{session}}=await sb.auth.getSession();if(session)await enter(session.user);else show('login');sb.auth.onAuthStateChange(async(e,s)=>{if(e==='SIGNED_IN'&&s)await enter(s.user);if(e==='SIGNED_OUT')show('login')})}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').classList.add('hidden');const {error}=await sb.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#login-error').textContent=error.message;$('#login-error').classList.remove('hidden')}};$('#logout').onclick=()=>sb.auth.signOut();$('#refresh').onclick=loadManagers;
async function enter(user){const {data,error}=await sb.from('admin_users').select('role,active').eq('user_id',user.id).maybeSingle();if(error||!data?.active||data.role!=='super_admin'){show('denied');return}show('dashboard');$('#admin-email').textContent=user.email;await loadBrands();await loadManagers()}
async function loadBrands(){const {data,error}=await sb.from('brands').select('*').order('sort_order');if(error)return toast('Lỗi brands: '+error.message);brands=data||[];$('#manager-brand').innerHTML=brands.map(b=>`<option value="${b.id}">${esc(b.name)}</option>`).join('');fillStores()}
function brandById(id){return brands.find(b=>Number(b.id)===Number(id))}function fillStores(){const b=brandById($('#manager-brand').value);const arr=Array.isArray(b?.locations)?b.locations:[];$('#manager-store').innerHTML=arr.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}$('#manager-brand').onchange=fillStores;
async function loadManagers(){const {data,error}=await sb.rpc('list_store_managers');if(error){$('#manager-list').innerHTML=`<div class="card p-6 text-red-600">${esc(error.message)}</div>`;return}managers=data||[];render()}
function render(){$('#manager-list').innerHTML=managers.map(m=>`<article class="card p-5"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="text-[10px] uppercase tracking-[.15em] text-primary font-bold">Store Manager</div><h3 class="font-bold text-base mt-1 truncate">${esc(m.email)}</h3></div><span class="text-[10px] px-2.5 py-1 rounded-full ${m.active?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'} font-bold">${m.active?'Hoạt động':'Tắt'}</span></div><div class="mt-4 rounded-2xl bg-bgLight p-4"><div class="font-bold text-secondary">${esc(m.brand_name||'')} · ${esc(m.store_location)}</div><div class="mt-3 flex flex-wrap gap-2 text-[10px]">${m.can_manage_products?'<span class="px-2 py-1 bg-white rounded-full border">Sản phẩm</span>':''}${m.can_manage_store_profile?'<span class="px-2 py-1 bg-white rounded-full border">Gian hàng</span>':''}${m.can_view_orders?'<span class="px-2 py-1 bg-white rounded-full border">Đơn hàng</span>':''}</div></div><button data-revoke="${m.user_id}" class="mt-4 w-full rounded-xl border border-red-200 text-red-600 py-2.5 text-xs font-bold">Thu hồi quyền</button></article>`).join('')||'<div class="card p-8 text-center text-gray-500 md:col-span-2 xl:col-span-3">Chưa có Store Manager.</div>';document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=()=>revoke(b.dataset.revoke))}
$('#assign-form').onsubmit=async e=>{e.preventDefault();const email=$('#manager-email').value.trim(),brandId=Number($('#manager-brand').value),store=$('#manager-store').value;if(!email||!brandId||!store)return;$('#assign-message').textContent='Đang cấp quyền...';const {error}=await sb.rpc('assign_store_manager_by_email',{p_email:email,p_brand_id:brandId,p_store_location:store,p_can_manage_products:$('#can-products').checked,p_can_manage_store_profile:$('#can-profile').checked,p_can_view_orders:$('#can-orders').checked});if(error){$('#assign-message').textContent='Lỗi: '+error.message;return}$('#assign-message').textContent='Đã cấp quyền. Nhân viên có thể đăng nhập catalog-admin.html bằng tài khoản này.';$('#manager-email').value='';await loadManagers();toast('Đã cập nhật quyền')}
async function revoke(userId){if(!confirm('Thu hồi toàn bộ quyền quản trị cửa hàng của tài khoản này?'))return;const {error}=await sb.rpc('revoke_store_manager',{p_user_id:userId});if(error)return toast('Lỗi: '+error.message);await loadManagers();toast('Đã thu hồi quyền')}
