import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const FALLBACK = {
  hero:{eyebrow_vi:'NANSHUO CAREERS 2026',eyebrow_zh:'南硕招贤纳士 2026',title_vi:'Nơi thời trang gặp những con người muốn tạo dấu ấn.',title_zh:'让时尚与渴望留下印记的人相遇。',text_vi:'Gia nhập Nanshuo Việt Nam và cùng phát triển hệ sinh thái thương hiệu thời trang hiện đại, nơi năng lực bán lẻ, sáng tạo và quản trị thương hiệu được trao cơ hội để bứt phá.',text_zh:'加入南硕越南，与我们共同打造现代时尚品牌生态，让零售、创意与品牌运营能力拥有更大的成长舞台。',image:'https://homesland.vn/blog/wp-content/uploads/2019/12/ban-royal-city-ve-dem-1280x720.jpg'},
  about:{title_vi:'Không chỉ tuyển người. Chúng tôi tìm những người muốn cùng thương hiệu lớn lên.',title_zh:'我们不只是招聘，更在寻找愿意与品牌共同成长的人。',text_vi:'Nanshuo Việt Nam vận hành và phát triển hệ sinh thái thời trang bán lẻ với nhiều thương hiệu, nhiều điểm bán và đội ngũ đa chức năng. Chúng tôi ưu tiên tốc độ học hỏi, tinh thần trách nhiệm, tư duy dịch vụ và khả năng biến ý tưởng thành kết quả.',text_zh:'南硕越南运营并发展多品牌、多门店的时尚零售生态。我们重视学习速度、责任感、服务意识，以及将创意转化为结果的能力。'},
  contact:{company:'CÔNG TY TNHH QUẢN LÝ THƯƠNG HIỆU NANSHUO VIỆT NAM',address:'Số 57, Louis VIII-LK29, KĐT mới Hoàng Văn Thụ, Hoàng Mai, Hà Nội, Việt Nam',email:'tuyendungnanshuo@gmail.com',phone:'0866 826 475',zalo:'0866826475'},
  brands:[
    {id:1,name:'WARRIOR',desc_vi:'Sneaker trẻ trung, năng động.',desc_zh:'青春活力运动鞋系列。',locations:['Times City','GO! Thăng Long'],image_url:'',active:true,sort_order:1},
    {id:2,name:'YANBABY',desc_vi:'Thời trang nữ dịu dàng, trẻ trung.',desc_zh:'温柔青春女装系列。',locations:['Royal City','Vincom Phạm Ngọc Thạch','GO! Thăng Long','Vincom Trần Duy Hưng','Times City','Vinhomes Ocean Park 2','Vincom Bắc Ninh'],image_url:'',active:true,sort_order:2},
    {id:3,name:'MERMAID',desc_vi:'Thời trang nữ hiện đại, thanh lịch.',desc_zh:'现代优雅女装。',locations:['Royal City','GO! Thăng Long','Times City','Vinhomes Smart City'],image_url:'',active:true,sort_order:3},
    {id:4,name:'GEK',desc_vi:'Phong cách tinh tế và trẻ trung.',desc_zh:'精致青春时尚风格。',locations:['Royal City','GO! Thăng Long','Vincom Trần Duy Hưng','Times City','Vinhomes Ocean Park 1'],image_url:'',active:true,sort_order:4},
    {id:5,name:'SANHE',desc_vi:'Trang phục mặc nhà chất lượng.',desc_zh:'高品质家居服饰。',locations:['Vincom Trần Duy Hưng','Times City'],image_url:'',active:true,sort_order:5}
  ],
  jobs:[
    {id:1,category:'ops',title_vi:'Quản Lý Cửa Hàng Bán Lẻ',title_zh:'零售店铺经理',location:'Hà Nội, Bắc Ninh, Thanh Hóa, Vinh, Việt Trì',type_vi:'Toàn thời gian · Xoay ca',type_zh:'全职 · 倒班',salary:'18–25 triệu + KPI',summary_vi:'Quản lý doanh thu, nhân sự và vận hành trực tiếp tại cửa hàng; đảm bảo chỉ tiêu và chất lượng dịch vụ.',summary_zh:'负责门店销售、人事与运营管理，确保业绩目标与服务质量。',hot:true,active:true,sort_order:1},
    {id:2,category:'ops',title_vi:'Nhân Viên Tư Vấn Bán Hàng Thời Trang',title_zh:'时尚销售顾问',location:'Hà Nội, Bắc Ninh, Thanh Hóa, Vinh, Việt Trì',type_vi:'Full-time / Part-time · Xoay ca',type_zh:'全职 / 兼职 · 灵活排班',salary:'8–12 triệu + Doanh số',summary_vi:'Tiếp cận, tìm hiểu nhu cầu và tư vấn sản phẩm; hỗ trợ hình ảnh cửa hàng, hàng hóa và trải nghiệm khách hàng.',summary_zh:'了解顾客需求并提供穿搭与商品建议，同时协助门店陈列、库存与顾客体验。',hot:true,active:true,sort_order:2},
    {id:3,category:'marketing',title_vi:'Fashion Brand Manager',title_zh:'时尚品牌经理',location:'Hoàng Mai, Hà Nội',type_vi:'Toàn thời gian',type_zh:'全职',salary:'Thỏa thuận',summary_vi:'Định hướng chiến lược, quản trị hình ảnh và lập kế hoạch phát triển các nhãn hàng thời trang.',summary_zh:'负责品牌战略、品牌形象与市场发展计划。',hot:false,active:true,sort_order:3},
    {id:4,category:'design',title_vi:'Graphic Designer · Fashion & Social',title_zh:'平面 / 视觉设计师',location:'Hoàng Mai, Hà Nội',type_vi:'Toàn thời gian',type_zh:'全职',salary:'15–22 triệu',summary_vi:'Thiết kế social campaign, POSM và đóng góp concept hình ảnh cho các thương hiệu thời trang.',summary_zh:'负责社媒创意、门店视觉物料与品牌拍摄概念。',hot:false,active:true,sort_order:4},
    {id:5,category:'marketing',title_vi:'Content Marketing · Fashion & Lifestyle',title_zh:'时尚内容营销专员',location:'Hoàng Mai, Hà Nội',type_vi:'Toàn thời gian',type_zh:'全职',salary:'12–18 triệu',summary_vi:'Sáng tạo nội dung, kịch bản video ngắn và bài viết quảng bá thương hiệu trên các nền tảng social.',summary_zh:'负责短视频脚本、社媒内容与品牌传播文案。',hot:false,active:true,sort_order:5}
  ]
};

const cfg=window.NANSHUO_CONFIG||{};
const configured=cfg.supabaseUrl&&cfg.supabaseKey&&!cfg.supabaseUrl.includes('PASTE_')&&!cfg.supabaseKey.includes('PASTE_');
let supabase=null; let data=structuredClone(FALLBACK); let lang=localStorage.getItem('nanshuo-lang')||'vi'; let activeCategory='all';
if(configured) supabase=createClient(cfg.supabaseUrl,cfg.supabaseKey);

const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function t(obj,viKey='title_vi',zhKey='title_zh'){return lang==='zh'?(obj[zhKey]||obj[viKey]||''):(obj[viKey]||obj[zhKey]||'')}
function setLang(next){lang=next;localStorage.setItem('nanshuo-lang',lang);document.documentElement.lang=lang;$('#lang-vi').className=`lang-btn text-[11px] font-extrabold rounded-full px-3 py-1.5 ${lang==='vi'?'bg-ink text-white':'text-gray-500'}`;$('#lang-zh').className=`lang-btn text-[11px] font-extrabold rounded-full px-3 py-1.5 ${lang==='zh'?'bg-ink text-white':'text-gray-500'}`;renderAll()}
async function loadData(){if(!supabase)return;try{const [settingsRes,brandsRes,jobsRes]=await Promise.all([supabase.from('site_settings').select('*').eq('id',1).maybeSingle(),supabase.from('brands').select('*').eq('active',true).order('sort_order'),supabase.from('jobs').select('*').eq('active',true).order('sort_order')]);if(settingsRes.data){data.hero=settingsRes.data.hero||data.hero;data.about=settingsRes.data.about||data.about;data.contact=settingsRes.data.contact||data.contact}if(brandsRes.data?.length)data.brands=brandsRes.data;if(jobsRes.data?.length)data.jobs=jobsRes.data;}catch(e){console.warn('Using fallback content',e)}}
function renderHero(){const h=data.hero;$('#hero-eyebrow').textContent=lang==='zh'?h.eyebrow_zh:h.eyebrow_vi;$('#hero-title').textContent=lang==='zh'?h.title_zh:h.title_vi;$('#hero-text').textContent=lang==='zh'?h.text_zh:h.text_vi;$('#hero-image').src=h.image||FALLBACK.hero.image;$('#hero-image').onerror=()=>{$('#hero-image').src=FALLBACK.hero.image};$('#stat-brands').textContent=String(data.brands.length).padStart(2,'0');$('#stat-jobs').textContent=String(data.jobs.filter(x=>x.active!==false).length).padStart(2,'0')}
function renderAbout(){const a=data.about;$('#about-title').textContent=lang==='zh'?a.title_zh:a.title_vi;$('#about-text').textContent=lang==='zh'?a.text_zh:a.text_vi}
function initials(name){return String(name||'N').split(/\s+/).map(x=>x[0]).join('').slice(0,3)}
function renderBrands(){const grid=$('#brand-grid');grid.innerHTML=data.brands.map((b,i)=>`<article class="brand-card reveal bg-white rounded-[26px] overflow-hidden border border-black/5 shadow-sm"><div class="aspect-[3/4] bg-gradient-to-br from-stone-200 to-stone-100 relative overflow-hidden">${b.image_url?`<img class="brand-image w-full h-full object-cover" src="${esc(b.image_url)}" alt="${esc(b.name)}" loading="lazy">`:`<div class="absolute inset-0 grid place-items-center"><div class="display text-4xl font-extrabold text-black/20">${esc(initials(b.name))}</div></div>`}<div class="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent"></div><div class="absolute left-5 right-5 bottom-5 text-white"><div class="display font-extrabold text-xl tracking-tight">${esc(b.name)}</div><div class="text-xs text-white/75 mt-1">${esc(lang==='zh'?b.desc_zh:b.desc_vi)}</div></div></div><div class="p-5"><div class="text-[10px] uppercase tracking-[.17em] font-bold text-gray-400"><i class="fa-solid fa-location-dot text-bronze mr-1"></i>${lang==='zh'?'门店':'Cửa hàng'}</div><div class="mt-3 flex flex-wrap gap-1.5">${(b.locations||[]).slice(0,4).map(x=>`<span class="text-[10px] bg-paper rounded-full px-2.5 py-1.5 text-gray-600">${esc(x)}</span>`).join('')}${(b.locations||[]).length>4?`<span class="text-[10px] bg-ink text-white rounded-full px-2.5 py-1.5">+${b.locations.length-4}</span>`:''}</div></div></article>`).join('');observeReveal()}
const cats=[['all','Tất cả','全部'],['ops','Bán lẻ','零售'],['marketing','Marketing & Brand','市场与品牌'],['design','Thiết kế','设计']];
function renderFilters(){const f=$('#job-filters');f.innerHTML=cats.map(([v,vi,zh])=>`<button data-cat="${v}" class="job-filter px-4 py-2.5 rounded-full text-xs font-bold border transition ${activeCategory===v?'bg-ink text-white border-ink':'bg-white border-black/10 text-gray-600 hover:border-black/25'}">${lang==='zh'?zh:vi}</button>`).join('');f.querySelectorAll('[data-cat]').forEach(btn=>btn.onclick=()=>{activeCategory=btn.dataset.cat;renderFilters();renderJobs()})}
function filteredJobs(){const q=$('#job-search').value.trim().toLowerCase();return data.jobs.filter(j=>j.active!==false).filter(j=>activeCategory==='all'||j.category===activeCategory).filter(j=>!q||[j.title_vi,j.title_zh,j.location,j.salary,j.summary_vi,j.summary_zh].join(' ').toLowerCase().includes(q))}
function renderJobs(){const list=$('#job-list'), jobs=filteredJobs();$('#jobs-empty').classList.toggle('hidden',jobs.length>0);list.innerHTML=jobs.map(j=>`<article class="bg-white border border-black/5 rounded-[26px] p-5 md:p-7 shadow-sm hover:shadow-soft hover:-translate-y-0.5 transition"><div class="flex flex-col md:flex-row md:items-center gap-5 justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2">${j.hot?`<span class="text-[9px] tracking-[.14em] uppercase font-extrabold bg-emerald/10 text-emerald rounded-full px-2.5 py-1">Hot</span>`:''}<span class="text-[10px] tracking-[.14em] uppercase font-bold text-gray-400">${esc(cats.find(c=>c[0]===j.category)?.[lang==='zh'?2:1]||j.category)}</span></div><h3 class="display text-xl md:text-2xl font-extrabold tracking-tight mt-2">${esc(lang==='zh'?j.title_zh:j.title_vi)}</h3><div class="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-xs text-gray-500"><span><i class="fa-solid fa-location-dot text-bronze mr-1.5"></i>${esc(j.location)}</span><span><i class="fa-regular fa-clock text-bronze mr-1.5"></i>${esc(lang==='zh'?j.type_zh:j.type_vi)}</span><span><i class="fa-solid fa-money-bill-wave text-emerald mr-1.5"></i>${esc(j.salary)}</span></div></div><button data-job-id="${j.id}" class="view-job flex-shrink-0 inline-flex items-center justify-center gap-2 rounded-full bg-ink text-white px-5 py-3.5 text-xs font-bold hover:bg-bronze transition"><span>${lang==='zh'?'查看详情':'Xem chi tiết'}</span><i class="fa-solid fa-arrow-right"></i></button></div></article>`).join('');list.querySelectorAll('.view-job').forEach(b=>b.onclick=()=>openJob(b.dataset.jobId))}
function openJob(id){const j=data.jobs.find(x=>String(x.id)===String(id));if(!j)return;$('#modal-hot').innerHTML=j.hot?'<span class="text-[9px] tracking-[.14em] uppercase font-extrabold bg-emerald/10 text-emerald rounded-full px-2.5 py-1">Hot</span>':'';$('#modal-title').textContent=lang==='zh'?j.title_zh:j.title_vi;$('#modal-meta').innerHTML=`<span class="bg-paper rounded-full px-3 py-2"><i class="fa-solid fa-location-dot text-bronze mr-1"></i>${esc(j.location)}</span><span class="bg-paper rounded-full px-3 py-2">${esc(lang==='zh'?j.type_zh:j.type_vi)}</span><span class="bg-paper rounded-full px-3 py-2">${esc(j.salary)}</span>`;$('#modal-summary').textContent=lang==='zh'?j.summary_zh:j.summary_vi;const subject=encodeURIComponent(`[Ứng tuyển] ${j.title_vi}`);$('#modal-apply').href=`mailto:${data.contact.email}?subject=${subject}`;$('#job-modal').classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModal(){$('#job-modal').classList.add('hidden');document.body.style.overflow=''}
function renderContact(){const c=data.contact;$('#company-name').textContent=c.company||'';$('#company-address').textContent=c.address||'';$('#footer-email').textContent=c.email||'';$('#footer-email').href=`mailto:${c.email||''}`;$('#footer-phone').textContent=c.phone||'';$('#footer-phone').href=`tel:${String(c.phone||'').replace(/\s/g,'')}`;$('#contact-email-btn').href=`mailto:${c.email||''}?subject=${encodeURIComponent('Ứng tuyển tại Nanshuo Việt Nam')}`}
function renderAll(){renderHero();renderAbout();renderBrands();renderFilters();renderJobs();renderContact()}
function observeReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal:not(.show)').forEach(el=>io.observe(el))}

$('#lang-vi').onclick=()=>setLang('vi');$('#lang-zh').onclick=()=>setLang('zh');$('#job-search').addEventListener('input',renderJobs);document.querySelectorAll('[data-close-modal]').forEach(x=>x.addEventListener('click',closeModal));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#year').textContent=new Date().getFullYear();
await loadData();setLang(lang);observeReveal();
