-- ================================================================
-- NANSHUO WEBSITE CMS - SUPABASE SETUP
-- Chạy toàn bộ file này trong Supabase > SQL Editor > New query
-- ================================================================

create table if not exists public.site_settings (
  id integer primary key,
  hero jsonb not null default '{}'::jsonb,
  about jsonb not null default '{}'::jsonb,
  contact jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint only_one_settings_row check (id = 1)
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  desc_vi text not null default '',
  desc_zh text not null default '',
  locations jsonb not null default '[]'::jsonb,
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  category text not null default 'ops',
  title_vi text not null,
  title_zh text not null default '',
  location text not null default '',
  type_vi text not null default 'Toàn thời gian',
  type_zh text not null default '全职',
  salary text not null default '',
  summary_vi text not null default '',
  summary_zh text not null default '',
  hot boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.site_settings enable row level security;
alter table public.brands enable row level security;
alter table public.jobs enable row level security;

drop policy if exists "public read site settings" on public.site_settings;
create policy "public read site settings" on public.site_settings for select to anon, authenticated using (true);
drop policy if exists "admin manage site settings" on public.site_settings;
create policy "admin manage site settings" on public.site_settings for all to authenticated using (true) with check (true);

drop policy if exists "public read active brands" on public.brands;
create policy "public read active brands" on public.brands for select to anon using (active = true);
drop policy if exists "authenticated read all brands" on public.brands;
create policy "authenticated read all brands" on public.brands for select to authenticated using (true);
drop policy if exists "admin manage brands" on public.brands;
create policy "admin manage brands" on public.brands for all to authenticated using (true) with check (true);

drop policy if exists "public read active jobs" on public.jobs;
create policy "public read active jobs" on public.jobs for select to anon using (active = true);
drop policy if exists "authenticated read all jobs" on public.jobs;
create policy "authenticated read all jobs" on public.jobs for select to authenticated using (true);
drop policy if exists "admin manage jobs" on public.jobs;
create policy "admin manage jobs" on public.jobs for all to authenticated using (true) with check (true);

-- Public bucket dùng cho ảnh hero / thương hiệu.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('site-images','site-images',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public=true, file_size_limit=6291456, allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "public read site images" on storage.objects;
create policy "public read site images" on storage.objects for select to public using (bucket_id = 'site-images');
drop policy if exists "admin insert site images" on storage.objects;
create policy "admin insert site images" on storage.objects for insert to authenticated with check (bucket_id = 'site-images');
drop policy if exists "admin update site images" on storage.objects;
create policy "admin update site images" on storage.objects for update to authenticated using (bucket_id = 'site-images') with check (bucket_id = 'site-images');
drop policy if exists "admin delete site images" on storage.objects;
create policy "admin delete site images" on storage.objects for delete to authenticated using (bucket_id = 'site-images');

-- Dữ liệu mặc định
insert into public.site_settings (id,hero,about,contact)
values (1,
'{"eyebrow_vi":"NANSHUO CAREERS 2026","eyebrow_zh":"南硕招贤纳士 2026","title_vi":"Nơi thời trang gặp những con người muốn tạo dấu ấn.","title_zh":"让时尚与渴望留下印记的人相遇。","text_vi":"Gia nhập Nanshuo Việt Nam và cùng phát triển hệ sinh thái thương hiệu thời trang hiện đại, nơi năng lực bán lẻ, sáng tạo và quản trị thương hiệu được trao cơ hội để bứt phá.","text_zh":"加入南硕越南，与我们共同打造现代时尚品牌生态，让零售、创意与品牌运营能力拥有更大的成长舞台。","image":"https://homesland.vn/blog/wp-content/uploads/2019/12/ban-royal-city-ve-dem-1280x720.jpg"}'::jsonb,
'{"title_vi":"Không chỉ tuyển người. Chúng tôi tìm những người muốn cùng thương hiệu lớn lên.","title_zh":"我们不只是招聘，更在寻找愿意与品牌共同成长的人。","text_vi":"Nanshuo Việt Nam vận hành và phát triển hệ sinh thái thời trang bán lẻ với nhiều thương hiệu, nhiều điểm bán và đội ngũ đa chức năng. Chúng tôi ưu tiên tốc độ học hỏi, tinh thần trách nhiệm, tư duy dịch vụ và khả năng biến ý tưởng thành kết quả.","text_zh":"南硕越南运营并发展多品牌、多门店的时尚零售生态。我们重视学习速度、责任感、服务意识，以及将创意转化为结果的能力。"}'::jsonb,
'{"company":"CÔNG TY TNHH QUẢN LÝ THƯƠNG HIỆU NANSHUO VIỆT NAM","address":"Số 57, Louis VIII-LK29, KĐT mới Hoàng Văn Thụ, Hoàng Mai, Hà Nội, Việt Nam","email":"tuyendungnanshuo@gmail.com","phone":"0866 826 475","zalo":"0866826475"}'::jsonb)
on conflict (id) do nothing;

insert into public.brands (name,desc_vi,desc_zh,locations,sort_order) 
select * from (values
('WARRIOR','Sneaker trẻ trung, năng động.','青春活力运动鞋系列。','["Times City","GO! Thăng Long"]'::jsonb,1),
('YANBABY','Thời trang nữ dịu dàng, trẻ trung.','温柔青春女装系列。','["Royal City","Vincom Phạm Ngọc Thạch","GO! Thăng Long","Vincom Trần Duy Hưng","Times City","Vinhomes Ocean Park 2","Vincom Bắc Ninh"]'::jsonb,2),
('MERMAID','Thời trang nữ hiện đại, thanh lịch.','现代优雅女装。','["Royal City","GO! Thăng Long","Times City","Vinhomes Smart City"]'::jsonb,3),
('GEK','Phong cách tinh tế và trẻ trung.','精致青春时尚风格。','["Royal City","GO! Thăng Long","Vincom Trần Duy Hưng","Times City","Vinhomes Ocean Park 1"]'::jsonb,4),
('SANHE','Trang phục mặc nhà chất lượng.','高品质家居服饰。','["Vincom Trần Duy Hưng","Times City"]'::jsonb,5)
) as v(name,desc_vi,desc_zh,locations,sort_order)
where not exists (select 1 from public.brands);

insert into public.jobs (category,title_vi,title_zh,location,type_vi,type_zh,salary,summary_vi,summary_zh,hot,sort_order)
select * from (values
('ops','Quản Lý Cửa Hàng Bán Lẻ','零售店铺经理','Hà Nội, Bắc Ninh, Thanh Hóa, Vinh, Việt Trì','Toàn thời gian · Xoay ca','全职 · 倒班','18–25 triệu + KPI','Quản lý doanh thu, nhân sự và vận hành trực tiếp tại cửa hàng; đảm bảo chỉ tiêu và chất lượng dịch vụ.','负责门店销售、人事与运营管理，确保业绩目标与服务质量。',true,1),
('ops','Nhân Viên Tư Vấn Bán Hàng Thời Trang','时尚销售顾问','Hà Nội, Bắc Ninh, Thanh Hóa, Vinh, Việt Trì','Full-time / Part-time · Xoay ca','全职 / 兼职 · 灵活排班','8–12 triệu + Doanh số','Tiếp cận, tìm hiểu nhu cầu và tư vấn sản phẩm; hỗ trợ hình ảnh cửa hàng, hàng hóa và trải nghiệm khách hàng.','了解顾客需求并提供穿搭与商品建议，同时协助门店陈列、库存与顾客体验。',true,2),
('marketing','Fashion Brand Manager','时尚品牌经理','Hoàng Mai, Hà Nội','Toàn thời gian','全职','Thỏa thuận','Định hướng chiến lược, quản trị hình ảnh và lập kế hoạch phát triển các nhãn hàng thời trang.','负责品牌战略、品牌形象与市场发展计划。',false,3),
('design','Graphic Designer · Fashion & Social','平面 / 视觉设计师','Hoàng Mai, Hà Nội','Toàn thời gian','全职','15–22 triệu','Thiết kế social campaign, POSM và đóng góp concept hình ảnh cho các thương hiệu thời trang.','负责社媒创意、门店视觉物料与品牌拍摄概念。',false,4),
('marketing','Content Marketing · Fashion & Lifestyle','时尚内容营销专员','Hoàng Mai, Hà Nội','Toàn thời gian','全职','12–18 triệu','Sáng tạo nội dung, kịch bản video ngắn và bài viết quảng bá thương hiệu trên các nền tảng social.','负责短视频脚本、社媒内容与品牌传播文案。',false,5)
) as v(category,title_vi,title_zh,location,type_vi,type_zh,salary,summary_vi,summary_zh,hot,sort_order)
where not exists (select 1 from public.jobs);
